#include "..\script_component.hpp"

#undef FNC_SUBPATH
#define FNC_SUBPATH xpiComponent

#define DIALOG_POS_LEFT 0
#define DIALOG_POS_CENTER 0.375
#define DIALOG_POS_RIGHT 0.75

#define DIALOG_ITEMS_COUNT_SMALL 5
#define DIALOG_ITEMS_COUNT_MEDIUM 3
#define DIALOG_ITEMS_COUNT_LARGE 2

#define DIALOG_ITEM_ICON_SIZE_SMALL 0.065
#define DIALOG_ITEM_ICON_SIZE_MEDIUM 0.105
#define DIALOG_ITEM_ICON_SIZE_LARGE 0.16

#define WEAPON_TYPE_NONE -1
#define WEAPON_TYPE_PRIMARY 0
#define WEAPON_TYPE_SECONDARY 1
#define WEAPON_TYPE_HANDGUN 2
