#define MAINPREFIX z
#define PREFIX dzn_XPI

#include "script_version.hpp"

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_ARR {MAJOR,MINOR,PATCHLVL,BUILD}

#define REQUIRED_VERSION 2.06
